// Generates styles/tokens.css: the 12-step OKLCH colour scales and the
// default ("default" style) semantic tokens. Run: node scripts/gen-tokens.mjs
import { writeFileSync } from 'node:fs';

// 12-step scales modelled on Radix Colors: 1-2 backgrounds, 3-5 component
// backgrounds, 6-8 borders, 9-10 solid fills, 11-12 text.
const GRAY_L = [0.991, 0.978, 0.955, 0.935, 0.914, 0.89, 0.855, 0.79, 0.64, 0.6, 0.5, 0.24];
const GRAY_L_DARK = [0.165, 0.195, 0.235, 0.265, 0.295, 0.33, 0.38, 0.46, 0.62, 0.67, 0.79, 0.95];

const ACCENT_L = [0.99, 0.975, 0.945, 0.915, 0.88, 0.84, 0.78, 0.7, null, null, 0.5, 0.28];
const ACCENT_L_DARK = [0.18, 0.205, 0.25, 0.285, 0.32, 0.365, 0.42, 0.5, null, null, 0.8, 0.93];
const ACCENT_K = [0.03, 0.07, 0.16, 0.26, 0.36, 0.46, 0.58, 0.76, 1, 1, 0.9, 0.55];
const ACCENT_K_DARK = [0.12, 0.16, 0.3, 0.4, 0.48, 0.56, 0.64, 0.76, 1, 1, 0.75, 0.3];

const gray = GRAY_L.map(
  (l, i) =>
    `  --mn-base-${i + 1}: light-dark(oklch(${l} var(--mn-gray-c) var(--mn-gray-h)), oklch(${GRAY_L_DARK[i]} var(--mn-gray-c) var(--mn-gray-h)));`,
).join('\n');

const lightness = (i, dark) => {
  if (i === 8) return dark ? 'var(--mn-tone-l9-dark, var(--mn-solid-l-dark))' : 'var(--mn-tone-l9, var(--mn-solid-l))';
  if (i === 9) return dark ? 'var(--mn-tone-l10-dark, var(--mn-solid-hover-l-dark))' : 'var(--mn-tone-l10, var(--mn-solid-hover-l))';
  return String(dark ? ACCENT_L_DARK[i] : ACCENT_L[i]);
};
const chroma = (k) => (k === 1 ? 'var(--mn-c)' : `calc(var(--mn-c) * ${k})`);

const accent = ACCENT_K.map(
  (k, i) =>
    `  --mn-accent-${i + 1}: light-dark(oklch(${lightness(i, false)} ${chroma(k)} var(--mn-h)), oklch(${lightness(i, true)} ${chroma(ACCENT_K_DARK[i])} var(--mn-h)));`,
).join('\n');

const css = `/* Generated by scripts/gen-tokens.mjs — edit the generator, not this file. */

@layer base {
  /* Brand hues. Override on :root (or any style scope) to re-brand. */
  :root {
    --mn-primary-h: 272;
    --mn-primary-c: 0.2;
    --mn-success-h: 152;
    --mn-success-c: 0.15;
    --mn-info-h: 238;
    --mn-info-c: 0.14;
    --mn-warning-h: 75;
    --mn-warning-c: 0.16;
    --mn-danger-h: 25;
    --mn-danger-c: 0.21;
  }

  /* Neutral scale: recomputed per style scope. */
  :root,
  [data-mn-style] {
    --mn-gray-h: 275;
    --mn-gray-c: 0.006;
${gray}
  }

  /* Accent scale: recomputed wherever the hue can change (scopes and tone-* elements). */
  :root,
  [data-mn-style],
  [class*='tone-'] {
    --mn-h: var(--mn-primary-h);
    --mn-c: var(--mn-primary-c);
${accent}
    --mn-accent-contrast: var(--mn-tone-contrast, var(--mn-on-accent));
  }

  /* A tone never inherits another tone's lightness overrides. */
  [class*='tone-'] {
    --mn-tone-l9: initial;
    --mn-tone-l9-dark: initial;
    --mn-tone-l10: initial;
    --mn-tone-l10-dark: initial;
    --mn-tone-contrast: initial;
  }

  /* Semantic tokens: the "default" style. Other styles override these. */
  :root,
  [data-mn-style] {
    --mn-solid-l: 0.56;
    --mn-solid-l-dark: 0.6;
    --mn-solid-hover-l: 0.51;
    --mn-solid-hover-l-dark: 0.66;
    --mn-on-accent: oklch(0.99 0 0);

    --mn-bg: var(--mn-base-1);
    --mn-fg: var(--mn-base-12);
    --mn-fg-muted: var(--mn-base-11);
    --mn-fg-subtle: var(--mn-base-10);
    --mn-surface: light-dark(oklch(1 0 0), oklch(0.205 var(--mn-gray-c) var(--mn-gray-h)));
    --mn-surface-2: var(--mn-base-2);
    --mn-surface-3: var(--mn-base-3);
    --mn-border: var(--mn-base-6);
    --mn-border-strong: var(--mn-base-8);
    --mn-edge: transparent;
    --mn-overlay: light-dark(oklch(0.22 0.02 var(--mn-gray-h) / 0.42), oklch(0 0 0 / 0.62));
    --mn-overlay-blur: 3px;

    --mn-surface-border: var(--mn-border);
    --mn-surface-shadow: 0 1px 2px light-dark(oklch(0 0 0 / 0.05), oklch(0 0 0 / 0.4)),
      0 1px 3px light-dark(oklch(0 0 0 / 0.05), oklch(0 0 0 / 0.3));
    --mn-surface-blur: 0px;

    --mn-popover: var(--mn-surface);
    --mn-popover-border: var(--mn-border);
    --mn-popover-shadow: 0 16px 36px -12px light-dark(oklch(0.2 0.02 var(--mn-gray-h) / 0.2), oklch(0 0 0 / 0.6)),
      0 2px 6px light-dark(oklch(0 0 0 / 0.06), oklch(0 0 0 / 0.4));

    --mn-tooltip: var(--mn-base-12);
    --mn-tooltip-fg: var(--mn-base-1);

    --mn-control: light-dark(oklch(1 0 0), oklch(0.19 var(--mn-gray-c) var(--mn-gray-h)));
    --mn-control-border: var(--mn-base-7);
    --mn-control-shadow: 0 1px 2px light-dark(oklch(0 0 0 / 0.04), oklch(0 0 0 / 0.2));
    --mn-inset-shadow: inset 0 1px 2px light-dark(oklch(0 0 0 / 0.06), oklch(0 0 0 / 0.3));

    --mn-track: var(--mn-base-5);
    --mn-thumb: oklch(1 0 0);
    --mn-thumb-shadow: 0 1px 3px oklch(0 0 0 / 0.25), 0 0 0 0.5px oklch(0 0 0 / 0.08);

    --mn-btn-shadow: 0 1px 2px oklch(0 0 0 / 0.12), inset 0 1px 0 oklch(1 0 0 / 0.12);
    --mn-btn-shadow-hover: var(--mn-btn-shadow);
    --mn-btn-shadow-active: 0 0 #0000;
    --mn-press-x: 0px;
    --mn-press-y: 0px;
    --mn-press-scale: 0.98;

    --mn-radius-control: 0.5rem;
    --mn-radius-surface: 0.875rem;
    --mn-radius-item: 0.375rem;
    --mn-radius-field: var(--mn-radius-control);
    --mn-radius-badge: 9999px;
    --mn-radius-check: 0.3rem;
    --mn-radius-thumb: 9999px;
    --mn-border-width: 1px;

    --mn-font-sans: 'Inter Variable', Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
    --mn-font-heading: var(--mn-font-sans);
    --mn-font-control: inherit;
    --mn-font-mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    --mn-btn-weight: 500;
    --mn-btn-transform: none;
    --mn-btn-tracking: normal;
    --mn-heading-weight: 650;
    --mn-heading-tracking: -0.02em;
    --mn-heading-transform: none;

    --mn-duration: 160ms;
    --mn-ease: cubic-bezier(0.2, 0, 0, 1);
  }
}
`;

writeFileSync(new URL('../styles/tokens.css', import.meta.url), css);
console.log('styles/tokens.css written');
